### 1. Import the numpy package under the name np 

In [2]:
import numpy as np


### 2. Print the numpy version and the configuration

In [ ]:
print(np.__version__)

### 3. Create a null vector of size 10

In [ ]:
null_vector = np.zeros(10)
print(null_vector)


### 4. How to find the memory size of any array


In [ ]:
arr = np.zeros((3, 4))
memory_size = arr.nbytes
print("Memory size of the array:", memory_size, "bytes")

### 5. How to get the documentation of the numpy add function from the command line?


In [ ]:
!pydoc numpy.add

### 6. Create a null vector of size 10 but the fifth value which is 1


In [ ]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

### 7. Create a vector with values ranging from 10 to 49



In [ ]:
vector = np.arange(10, 50)
print(vector)

### 8. Reverse a vector (first element becomes last)



In [ ]:
vector = np.arange(10, 50)
reversed_vector = vector[::-1]
print(reversed_vector)

### 9. Create a 3x3 matrix with values ranging from 0 to 8


In [ ]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

### 10. Find indices of non-zero elements from [1,2,0,0,4,0]


In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)
print(indices)

### 11. Create a 3x3 identity matrix


In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)

### 12. Create a 3x3x3 array with random values


In [ ]:
array = np.random.rand(3, 3, 3)
print(array)

##### 13. Create a 10x10 array with random values and find the minimum and maximum values 


In [ ]:
array = np.random.rand(10, 10)
print("Array:")
print(array)

minimum_value = np.min(array)
maximum_value = np.max(array)

print("Minimum value:", minimum_value)
print("Maximum value:", maximum_value)

#### 14. Create a random vector of size 30 and find the mean value


In [ ]:
import numpy as np

vector = np.random.rand(30)
print("Vector:")
print(vector)

mean_value = np.mean(vector)
print("Mean value:", mean_value)

#### 15. Create a 2D array with 1 on the border and 0 inside



In [4]:
rows = 6
cols = 6

array = np.zeros((rows, cols))
array[0, :] = 1  # Top row
array[-1, :] = 1  # Bottom row
array[:, 0] = 1  # Left column
array[:, -1] = 1  # Right column

print(array)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array


In [6]:
existing_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

border_width = 2

padded_array = np.pad(existing_array, pad_width=border_width, mode='constant')

print("Existing Array:")
print(existing_array)

print("\nPadded Array:")
print(padded_array)


Existing Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Padded Array:
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0]
 [0 0 4 5 6 0 0]
 [0 0 7 8 9 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


#### 17. Results of the given expression


In [7]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1


False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal


In [8]:
matrix = np.zeros((5, 5))
diagonal_values = [1, 2, 3, 4]

# Assign values just below the diagonal
np.fill_diagonal(matrix[1:], diagonal_values)

print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern



In [ ]:
matrix = np.zeros((8, 8), dtype=str)
matrix[::2, ::2] = "★"  # Set stars in even rows and even columns
matrix[1::2, 1::2] = "★"  # Set stars in odd rows and odd columns
print(matrix)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element


In [ ]:
array_shape = (6, 7, 8)
total_elements = np.prod(array_shape)  # Compute the total number of elements in the array
element_index = 100

# Check if the element index is within the valid range
if element_index >= total_elements:
    print("Element index is out of range for the given array shape.")
else:
    # Compute the index (x, y, z) of the element
    indices = np.unravel_index(element_index, array_shape)
    print("Index (x, y, z) of the 100th element:", indices)

#### 21. Create a checkerboard 8x8 matrix using the tile function




In [ ]:
base_pattern = np.array([[0, 1], [1, 0]])
checkerboard = np.tile(base_pattern, (4, 4))

print(checkerboard)

#### 22. Normalize a 5x5 random matrix

In [ ]:
random_matrix = np.random.random((5, 5))
normalized_matrix = np.linalg.norm(random_matrix)

print("Random Matrix:")
print(random_matrix)

print("\nNormalized Matrix:")
print(normalized_matrix)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)


In [ ]:
# Define the custom dtype
color_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])
# Create a color array using the custom dtype
color_array = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=color_dtype)
print(color_array)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)


In [ ]:
matrix1 = np.random.random((5, 3))
matrix2 = np.random.random((3, 2))

product = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nMatrix Product:")
print(product)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.



In [9]:
arr = np.array([1, 5, 4, 9, 7, 2, 6, 3, 8])

# Find the indices of elements between 3 and 8
indices = np.where((arr >= 3) & (arr <= 8))

# Negate the elements at the found indices
arr[indices] = -arr[indices]

print(arr)

[ 1 -5 -4  9 -7  2 -6 -3 -8]


#### 26. What is the output of the following script


In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

#### 28. What are the result of the following expressions


In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

#### 29. How to round away from zero a float array



In [ ]:
arr = np.array([-1.5, 2.3, -4.7, 5.9, -0.1])

rounded_arr = np.ceil(np.abs(arr)) * np.copysign(1, arr)

print(rounded_arr)

#### 30. How to find common values between two arrays



In [ ]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

common_values = np.intersect1d(array1, array2)

print(common_values)

#### 31. How to ignore all numpy warnings (not recommended)



In [ ]:
import numpy as np
import warnings

# Ignore all NumPy warnings
warnings.filterwarnings('ignore', category=FutureWarning)

# Reset warnings to default behavior
warnings.resetwarnings()

#### 32. Is the following expressions true?


In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

#### 33. How to get the dates of yesterday, today and tomorrow



In [ ]:
from datetime import datetime, timedelta

# Get today's date
today = datetime.now().date()

# Get yesterday's date
yesterday = today - timedelta(days=1)

# Get tomorrow's date
tomorrow = today + timedelta(days=1)

# Print the dates
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

#### 34. How to get all the dates corresponding to the month of July 2016



In [ ]:
from datetime import datetime, timedelta

def get_dates_in_month(year, month):
    start_date = datetime(year, month, 1).date()
    next_month = start_date.replace(day=28) + timedelta(days=4)  # Add 4 days to go beyond end of month
    end_date = next_month - timedelta(days=next_month.day)

    dates_in_month = []
    current_date = start_date
    while current_date <= end_date:
        dates_in_month.append(current_date)
        current_date += timedelta(days=1)

    return dates_in_month

# Get all dates in July 2016
dates_july_2016 = get_dates_in_month(2016, 7)

# Print the dates
for date in dates_july_2016:
    print(date)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)




In [ ]:
A = np.array([1, 2, 3], dtype=float)
B = np.array([4, 5, 6])

# Compute ((A+B)*(-A/2)) in place
np.add(A, B, out=A)
np.negative(A, out=A)
np.divide(A, 2, out=A)

# Print the result
print(A)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods

In [ ]:

# Generate a random array of positive numbers
arr = np.random.rand(5) * 10  # Adjust the size of the array as needed

# Method 1: Using np.floor()
int_part_1 = np.floor(arr)
print("Method 1 (np.floor()):", int_part_1)

# Method 2: Using np.trunc()
int_part_2 = np.trunc(arr)
print("Method 2 (np.trunc()):", int_part_2)

# Method 3: Using np.ceil() and subtraction
int_part_3 = arr - (arr % 1)
print("Method 3 (np.ceil() and subtraction):", int_part_3)

# Method 4: Using np.astype()
int_part_4 = arr.astype(int)
print("Method 4 (np.astype()):", int_part_4)

Method 1 (np.floor()): [1. 2. 7. 3. 1.]
Method 2 (np.trunc()): [1. 2. 7. 3. 1.]
Method 3 (np.ceil() and subtraction): [1. 2. 7. 3. 1.]
Method 4 (np.astype()): [1 2 7 3 1]



#### 37. Create a 5x5 matrix with row values ranging from 0 to 4


In [ ]:

# Create a 1-dimensional array ranging from 0 to 4
row_values = np.arange(5)

# Create a 5x5 matrix by broadcasting the row values
matrix = np.tile(row_values, (5, 1))

# Print the matrix
print(matrix)

#### 38. Consider a generator function that generates 10 integers and use it to build an array


In [ ]:
def integer_generator():
    for i in range(10):
        yield i

# Create an array using the generator function
array = np.fromiter(integer_generator(), dtype=int)

# Print the array
print(array)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [ ]:
vector = np.linspace(0, 1, 10, endpoint=False)[1:]

# Print the vector
print(vector)

#### 40. Create a random vector of size 10 and sort it (★★☆)



In [ ]:
# Create a random vector of size 10
vector = np.random.rand(10)

# Sort the vector
sorted_vector = np.sort(vector)

# Print the sorted vector
print(sorted_vector)

#### 41. How to sum a small array faster than np.sum? (★★☆)


In [ ]:
import math
arr = [1, 2, 3, 4, 5]
total = sum(arr)


arr = [1.1, 2.2, 3.3, 4.4, 5.5]
total = math.fsum(arr)

#### 42. Consider two random array A and B, check if they are equal (★★☆)


In [ ]:
# Generate two random arrays A and B
A = np.random.rand(5)
B = np.random.rand(5)

# Check if A and B are equal
are_equal = np.array_equal(A, B)

# Print the result
print(are_equal)


"""
#### 43. Make an array immutable (read-only) (★★☆)


In [ ]:
mutable_array = np.array([1, 2, 3, 4, 5])

# Make the array immutable
immutable_array = mutable_array.copy()
immutable_array.flags.writeable = False

# Try to modify the immutable array (raises an error)
immutable_array[0] = 10
"""

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)


In [ ]:

# Create a random 10x2 matrix representing Cartesian coordinates
cartesian_coords = np.random.rand(10, 2)

# Convert Cartesian coordinates to polar coordinates
x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]
r = np.hypot(x, y)
theta = np.arctan2(y, x)

# Stack r and theta to form a 10x2 matrix representing polar coordinates
polar_coords = np.column_stack((r, theta))

# Print the polar coordinates
print(polar_coords)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)


In [ ]:
# Create a random vector of size 10
vector = np.random.rand(10)

# Find the maximum value in the vector
max_value = np.max(vector)

# Replace the maximum value with 0
vector[vector == max_value] = 0

# Print the updated vector
print(vector)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)


In [ ]:
# Define the number of points in each dimension
num_points = 5

# Create a grid of x and y coordinates
x_coords = np.linspace(0, 1, num_points)
y_coords = np.linspace(0, 1, num_points)
xx, yy = np.meshgrid(x_coords, y_coords)

# Create a structured array
structured_array = np.zeros((num_points*num_points,), dtype=[('x', float), ('y', float)])
structured_array['x'] = xx.flatten()
structured_array['y'] = yy.flatten()

# Print the structured array
print(structured_array)


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)


In [ ]:

# Example arrays X and Y
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

# Compute the Cauchy matrix
C = 1 / (X[:, np.newaxis] - Y)

# Print the Cauchy matrix
print(C)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)


In [ ]:
# Integer scalar types
integer_types = [np.int8, np.int16, np.int32, np.int64,
                 np.uint8, np.uint16, np.uint32, np.uint64]

for int_type in integer_types:
    info = np.iinfo(int_type)
    print(f"{int_type.__name__}: min={info.min}, max={info.max}")

# Floating-point scalar types
float_types = [np.float16, np.float32, np.float64]

for float_type in float_types:
    info = np.finfo(float_type)
    print(f"{float_type.__name__}: min={info.min}, max={info.max}")


#### 49. How to print all the values of an array? (★★☆)




In [ ]:
# Create an example array
arr = np.array([1, 2, 3, 4, 5])
# Print all the values of the array
print(arr)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)


In [ ]:
# Example vector
vector = np.array([1, 4, 7, 10])

# Target scalar
target = 6

# Find the index of the closest value
index = np.abs(vector - target).argmin()

# Get the closest value
closest_value = vector[index]

# Print the closest value
print(closest_value)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:


# Define the structured data type
dtype = np.dtype([('position', [('x', float), ('y', float)]),
                  ('color', [('r', int), ('g', int), ('b', int)])])

# Create a structured array
structured_array = np.array([((1.0, 2.0), (255, 0, 0)),
                             ((3.0, 4.0), (0, 255, 0)),
                             ((5.0, 6.0), (0, 0, 255))], dtype=dtype)

# Print the structured array
print(structured_array)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [ ]:

import numpy as np

# Generate random vector with shape (100, 2)
random_vector = np.random.rand(100, 2)

# Calculate point-by-point distances
distances = np.zeros((100, 100))  # Initialize an empty distance matrix

for i in range(100):
    for j in range(100):
        x1, y1 = random_vector[i]  # Coordinates of point i
        x2, y2 = random_vector[j]  # Coordinates of point j
        distances[i, j] = np.sqrt((x2 - x1)**2 + (y2 - y1)**2)

print(distances)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:

# Create a float array with 32-bit precision
float_array = np.array([1.5, 2.7, 3.3], dtype=np.float32)
print("Float array:", float_array)

# Convert the float array to an integer array in place
int_array = float_array.view(np.int32)
print("Integer array:", int_array)

#### 54. How to read the following file? (★★☆)

In [ ]:
"""
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
    _summary_
    
data = []

with open(filename, 'r') as file:
    csv_reader = csv.reader(file, delimiter=',')
    for row in csv_reader:
        stripped_row = [cell.strip() for cell in row]
        data.append(stripped_row)

print(data)

"""

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:

## The equivalent of enumerate for NumPy arrays is the np.ndenumerate function.
arr = np.array([[1, 2, 3], [4, 5, 6]])

for index, value in np.ndenumerate(arr):
    print(index, value)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:

from scipy.stats import multivariate_normal

# Define parameters for the Gaussian distribution
mean = [0, 0]  # Mean of the distribution
cov = [[1, 0], [0, 1]]  # Covariance matrix

# Generate a 2D grid of coordinates
x = np.linspace(-3, 3, 100)
y = np.linspace(-3, 3, 100)
X, Y = np.meshgrid(x, y)
pos = np.dstack((X, Y))

# Calculate the Gaussian distribution values at each coordinate
Z = multivariate_normal.pdf(pos, mean, cov)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:

# Define the size of the 2D array
rows = 5
cols = 5

# Define the number of elements to randomly place
p = 5

# Create an empty 2D array
arr = np.zeros((rows, cols))

# Generate random indices for placing the elements
indices = np.random.choice(rows * cols, p, replace=False)

# Set the randomly chosen indices to 1
arr.flat[indices] = 1

# Print the resulting array
print(arr)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:

# Create a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Subtract the mean of each row
mean_subtracted = matrix - np.mean(matrix, axis=1, keepdims=True)

# Print the result
print(mean_subtracted)

#### 59. How to sort an array by the nth column? (★★☆)


In [ ]:

# Create an array
arr = np.array([[1, 4, 7],
                [2, 5, 8],
                [3, 6, 9]])

# Sort the array by the nth column (0-based indexing)
n = 1
sorted_arr = arr[arr[:, n].argsort()]

# Print the sorted array
print(sorted_arr)

#### 60. How to tell if a given 2D array has null columns? (★★☆)



In [ ]:
# Create a 2D array
arr = np.array([[1, 2, 3],
                [0, 0, 0],
                [4, 5, 6],
                [0, 0, 0]])

# Check if any columns are null
is_null_column = np.all(arr == 0, axis=0)

# Print the result
print(is_null_column)

#### 61. Find the nearest value from a given value in an array (★★☆)


In [ ]:


# Create an array
arr = np.array([1, 3, 7, 9, 15])

# Given value
value = 8

# Find the nearest value
nearest_value = arr[np.abs(arr - value).argmin()]

# Print the result
print(nearest_value)


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)


In [ ]:

# Create the arrays
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4], [5], [6]])

# Get the iterators
iter1 = np.nditer(arr1)
iter2 = np.nditer(arr2)

# Compute the sum using the iterators
sum_result = 0
for x, y in zip(iter1, iter2):
    sum_result += (x + y)

# Print the result
print(sum_result)


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray:
    def __init__(self, name, array):
        self.name = name
        self.array = array

    def __str__(self):
        return f"Name: {self.name}\nArray: {self.array}"

# Create an instance of the NamedArray class
arr = NamedArray("MyArray", [1, 2, 3, 4, 5])

# Access the name attribute
print(arr.name)  # Output: MyArray

# Access the array attribute
print(arr.array)  # Output: [1, 2, 3, 4, 5]

# Print the NamedArray instance

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:

# Given vector
vector = np.array([1, 2, 3, 4, 5])

# Index vector
indices = np.array([0, 1, 3, 1, 4])

# Create a copy of the vector
result = vector.copy()

# Add 1 to each element indexed by the second vector
np.add.at(result, indices, 1)

# Print the result
print(result)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)


In [ ]:



# Define the vector X and index list I
X = np.array([1, 2, 3, 4, 5])
I = np.array([0, 1, 1, 2, 2])

# Calculate the size of the output array F
F_size = np.max(I) + 1

# Initialize the output array F with zeros
F = np.zeros(F_size)

# Accumulate elements of X into F based on the indices in I
np.add.at(F, I, X)

print(F)


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:



# Generate a random image with dimensions (w, h, 3)
w, h = 100, 100
image = np.random.randint(0, 256, size=(w, h, 3), dtype=np.uint8)

# Reshape the image to a 2D array with shape (w * h, 3)
reshaped_image = image.reshape(-1, 3)

# Compute the number of unique colors
unique_colors = np.unique(reshaped_image, axis=0)

# Get the number of unique colors
num_unique_colors = len(unique_colors)

print("Number of unique colors:", num_unique_colors)

#### 67. Considering a four dimensions array, how to get sum over the last 

In [ ]:
two axis at once? (★★★)
# Create a four-dimensional array
array = np.random.randint(0, 10, size=(2, 3, 4, 5))

# Compute the sum over the last two axes
sum_last_two_axes = np.sum(array, axis=(-2, -1))

# Print the result
print(sum_last_two_axes)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)


In [ ]:

# Create the one-dimensional vector D
D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Create the subset indices vector S
S = np.array([0, 0, 1, 1, 1, 2, 2, 2, 2, 2])

# Compute the means of the subsets
means = np.bincount(S, weights=D) / np.bincount(S)

# Print the result
print(means)


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:

# Create two matrices A and B
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

# Compute the dot product of A and B
dot_product = np.einsum('ij, jk -> ik', A, B)

# Get the diagonal elements of the dot product
diagonal = np.diagonal(dot_product)

# Print the result
print(diagonal)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:



# Create the original vector
original_vector = np.array([1, 2, 3, 4, 5])

# Number of consecutive zeros to insert
zeros_count = 3

# Compute the length of the new vector
new_length = original_vector.size + (original_vector.size - 1) * zeros_count

# Create an array of zeros with the appropriate length
zeros = np.zeros(new_length, dtype=original_vector.dtype)

# Insert the original values and zeros at the correct positions
zeros[::zeros_count + 1] = original_vector

# Print the result
print(zeros)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:

# Create a three-dimensional array A with dimensions (5, 5, 3)
A = np.random.random((5, 5, 3))

# Create a two-dimensional array B with dimensions (5, 5)
B = np.random.random((5, 5))

# Multiply array A by array B
result = A * B[:, :, np.newaxis]

# Print the result
print(result)

#### 72. How to swap two rows of an array? (★★★)


In [ ]:

# Create a 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Swap rows 1 and 2
array[1], array[2] = array[2], array[1]

# Print the result
print(array)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)


In [ ]:

# Set of 10 triplets describing triangles
triplets = np.array([[1, 2, 3],
                     [2, 3, 4],
                     [3, 4, 5],
                     [4, 5, 6],
                     [5, 6, 7],
                     [6, 7, 8],
                     [7, 8, 9],
                     [8, 9, 10],
                     [9, 10, 11],
                     [10, 11, 12]])

# Reshape the triplets to form line segments
line_segments = triplets.reshape(-1, 2)

# Sort each line segment to ensure consistency
line_segments.sort(axis=1)

# Find the unique line segments
unique_segments = np.unique(line_segments, axis=0)

# Print the result
print(unique_segments)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)


In [ ]:

# Sorted array C corresponding to bincount
C = np.array([0, 1, 2, 2, 3, 4, 4, 4, 5])

# Produce array A such that np.bincount(A) == C
A = np.repeat(np.arange(len(C)), C)

# Print the result
print(A)

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:

# Input array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Window size
window_size = 3

# Define the weights for the sliding window
weights = np.ones(window_size) / window_size

# Compute the averages using the sliding window
averages = np.convolve(array, weights, mode='valid')

# Print the result
print(averages)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:


b = True
b = not b
print(b)  # False

f = 3.14
f *= -1
print(f)  # -3.14

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)


In [ ]:

def distance_to_lines(P0, P1, p):
    # Convert points to NumPy arrays
    P0 = np.array(P0)
    P1 = np.array(P1)
    p = np.array(p)

    # Compute vectors along each line segment
    v = P1 - P0

    # Compute vectors from P0 to p
    w = p - P0

    # Compute dot products
    dot_products = np.einsum('ij,ij->i', v, w)

    # Compute squared lengths of each line segment
    squared_lengths = np.einsum('ij,ij->i', v, v)

    # Compute distances from p to each line
    distances = np.abs(dot_products) / np.sqrt(squared_lengths)

    return distances

# Example usage
P0 = [(1, 1), (2, 2), (3, 3)]
P1 = [(4, 4), (5, 5), (6, 6)]
p = (2, 5)

distances = distance_to_lines(P0, P1, p)
print(distances)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)


In [ ]:


def distance_to_lines(P0, P1, P):
    # Convert points to NumPy arrays
    P0 = np.array(P0)
    P1 = np.array(P1)
    P = np.array(P)

    # Compute vectors along each line segment
    v = P1 - P0

    # Initialize array to store distances
    distances = np.zeros((len(P), len(P0)))

    # Compute distances from each point in P to each line
    for i, p in enumerate(P):
        w = p - P0
        dot_products = np.sum(v * w, axis=1)
        squared_lengths = np.sum(v * v, axis=1)
        distances[i] = np.abs(dot_products) / np.sqrt(squared_lengths)

    return distances

# Example usage
P0 = [(1, 1), (2, 2), (3, 3)]
P1 = [(4, 4), (5, 5), (6, 6)]
P = [(2, 5), (3, 4), (4, 3)]

distances = distance_to_lines(P0, P1, P)
print(distances)


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)


In [ ]:

def extract_subpart(arr, shape, center, fill_value):
    # Convert inputs to NumPy arrays
    arr = np.array(arr)
    shape = np.array(shape)

    # Calculate the starting and ending indices for each dimension
    start = np.maximum(center - shape // 2, 0)
    end = np.minimum(start + shape, arr.shape)

    # Create an empty array with the desired shape and fill it with the fill value
    subpart = np.full(shape, fill_value)

    # Calculate the indices for the subpart within the full array
    subpart_start = start - (center - shape // 2)
    subpart_end = subpart_start + (end - start)

    # Copy the relevant portion from the full array to the subpart array
    subpart[subpart_start[0]:subpart_end[0], subpart_start[1]:subpart_end[1]] = arr[start[0]:end[0], start[1]:end[1]]

    return subpart

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)


In [ ]:
from numpy.lib.stride_tricks import sliding_window_view

Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
window_size = 4

R = sliding_window_view(Z, window_shape=(window_size,))
print(R)

#### 82. Compute a matrix rank (★★★)

In [ ]:


# Create a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Compute the rank of the matrix
rank = np.linalg.matrix_rank(matrix)

print("Rank:", rank)

#### 83. How to find the most frequent value in an array?

In [ ]:


# Create an array
arr = np.array([1, 2, 3, 2, 4, 2, 1, 3, 2, 2])

# Count the occurrences of each value
counts = np.bincount(arr)

# Find the value with the maximum count
most_frequent_value = np.argmax(counts)

print("Most frequent value:", most_frequent_value)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:

# Create a random 10x10 matrix
matrix = np.random.randint(0, 10, (10, 10))

# Extract the contiguous 3x3 blocks
blocks = []
for i in range(8):  # Iterate over rows (0 to 7)
    for j in range(8):  # Iterate over columns (0 to 7)
        block = matrix[i:i+3, j:j+3]  # Extract the 3x3 block
        blocks.append(block)

# Display the extracted blocks
for block in blocks:
    print(block)
    print()

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)


In [ ]:

class SymmetricArray(np.ndarray):
    def __getitem__(self, index):
        # Swap the indices for symmetry
        swapped_index = (index[1], index[0])
        return super().__getitem__(swapped_index)

# Create a symmetric 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sym_arr = arr.view(SymmetricArray)

# Test the symmetry property
print(sym_arr[0, 1])  # Output: 2
print(sym_arr[1, 0])  # Output: 2

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)


In [ ]:

# Set the number of matrices and their shape
p = 3
n = 4

# Create p matrices and p vectors
matrices = [np.random.rand(n, n) for _ in range(p)]
vectors = [np.random.rand(n, 1) for _ in range(p)]

# Compute the sum of p matrix products
result = np.sum([np.matmul(matrices[i], vectors[i]) for i in range(p)], axis=0)

print(result)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:

# Create a 16x16 array
arr = np.arange(256).reshape(16, 16)

# Define the block size
block_size = 4

# Reshape the array to a block-shaped 4D array
block_arr = arr.reshape(4, 4, 4, 4)

# Compute the block-sum along the last two axes
block_sum = np.sum(block_arr, axis=(-2, -1))

print(block_sum)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:

def game_of_life(grid, iterations):
    """
    Simulates the Game of Life for a given number of iterations.

    Args:
        grid (numpy.ndarray): The initial grid of cells.
        iterations (int): The number of iterations to simulate.

    Returns:
        numpy.ndarray: The final grid of cells after the specified number of iterations.
    """

    for _ in range(iterations):
        # Create a copy of the current grid for the next iteration
        next_grid = grid.copy()

        # Get the number of rows and columns in the grid
        rows, cols = grid.shape

        # Iterate over each cell in the grid
        for i in range(rows):
            for j in range(cols):
                # Count the number of live neighbors
                live_neighbors = np.sum(grid[max(i-1, 0):min(i+2, rows), max(j-1, 0):min(j+2, cols)]) - grid[i, j]

                # Apply the rules of the Game of Life
                if grid[i, j] == 1 and (live_neighbors < 2 or live_neighbors > 3):
                    next_grid[i, j] = 0
                elif grid[i, j] == 0 and live_neighbors == 3:
                    next_grid[i, j] = 1

        # Update the grid for the next iteration
        grid = next_grid

    return grid

#### 89. How to get the n largest values of an array (★★★)


In [ ]:

# Create an array of random numbers
arr = np.random.randint(0, 100, 20)

# Number of largest values to retrieve
n = 5

# Get the n largest values
largest_values = -np.partition(-arr, n)[:n]

print(largest_values)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)


In [ ]:

import itertools

# Define the vectors
vector1 = [1, 2]
vector2 = ['a', 'b', 'c']
vector3 = [True, False]

# Build the cartesian product
cartesian_product = list(itertools.product(vector1, vector2, vector3))

print(cartesian_product)

#### 91. How to create a record array from a regular array? (★★★)

In [ ]:


# Create a regular array
regular_array = np.array([(1, 'Alice', 25),
                          (2, 'Bob', 30),
                          (3, 'Charlie', 35)],
                         dtype=[('id', int), ('name', 'U10'), ('age', int)])

# Create a record array from the regular array
record_array = np.rec.array(regular_array)

print(record_array)
print(record_array.id)
print(record_array.name)
print(record_array.age)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)


In [ ]:

# Create a large vector Z
Z = np.random.rand(1000000)

# Compute Z to the power of 3 using NumPy's power function
result1 = np.power(Z, 3)

# Compute Z to the power of 3 using a loop
result3 = np.empty_like(Z)
for i in range(len(Z)):
    result3[i] = Z[i] ** 3

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)


In [ ]:

# Create arrays A and B
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [1, 2, 9],
              [4, 6, 5],
              [7, 9, 8],
              [1, 2, 3],
              [4, 5, 6]])

B = np.array([[1, 2],
              [4, 5]])

# Find rows of A that contain elements of each row of B
rows = np.where(np.logical_and.reduce(np.isin(A, B), axis=1))[0]

print(rows)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:

# Create a 10x3 matrix
matrix = np.array([[1, 2, 3],
                   [2, 2, 2],
                   [4, 5, 6],
                   [7, 7, 7],
                   [1, 2, 9],
                   [4, 6, 5],
                   [7, 9, 9],
                   [1, 2, 3],
                   [4, 5, 6],
                   [1, 1, 1]])

# Extract rows with unequal values
unequal_rows = matrix[~np.all(matrix == matrix[0, :], axis=1)]

print(unequal_rows)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)


In [ ]:


# Create a vector of integers
vector = np.array([5, 3, 1, 7])

# Get the maximum value in the vector
max_value = np.max(vector)

# Determine the number of bits required to represent the maximum value
num_bits = int(np.ceil(np.log2(max_value + 1)))

# Convert the vector into a matrix binary representation
binary_matrix = np.unpackbits(vector.astype(np.uint8)[:, np.newaxis], axis=1)
binary_matrix = binary_matrix[:, -num_bits:]

print(binary_matrix)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:

# Create a two-dimensional array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [1, 2, 3],
                  [7, 8, 9],
                  [4, 5, 6]])

# Extract unique rows
unique_rows = np.unique(array, axis=0)

print(unique_rows)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)


In [ ]:



# Define vectors A and B
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Inner product of A and B
inner_product = np.einsum('i,i', A, B)
print("Inner product:", inner_product)

# Outer product of A and B
outer_product = np.einsum('i,j->ij', A, B)
print("Outer product:")
print(outer_product)

# Element-wise sum of A and B
elementwise_sum = np.einsum('i,i->i', A, B)
print("Element-wise sum:", elementwise_sum)

# Element-wise multiplication of A and B
elementwise_multiply = np.einsum('i,i->i', A, B)
print("Element-wise multiplication:", elementwise_multiply)



#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?


In [ ]:

# Define vectors X and Y
X = np.array([1, 2, 3, 4, 5])
Y = np.array([10, 20, 30, 40, 50])

# Number of samples
num_samples = 10

# Calculate the total length of the path
path_length = np.sum(np.sqrt(np.diff(X) ** 2 + np.diff(Y) ** 2))

# Calculate the step size
step_size = path_length / (num_samples - 1)

# Calculate the cumulative distances along the path
distances = np.cumsum(np.sqrt(np.diff(X) ** 2 + np.diff(Y) ** 2))

# Add zero at the beginning to represent the starting point
distances = np.insert(distances, 0, 0)

# Sample the path using equidistant samples
sampled_X = np.interp(np.linspace(0, path_length, num_samples), distances, X)
sampled_Y = np.interp(np.linspace(0, path_length, num_samples), distances, Y)

# Print the sampled path
for x, y in zip(sampled_X, sampled_Y):
    print(f"({x}, {y})")

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)


In [ ]:

# Define the integer n and the 2D array X
n = 5
X = np.array([[1, 2, 2],
              [0, 5, 0],
              [2, 1, 2],
              [3, 0, 2]])

# Select rows that only contain integers and sum to n
selected_rows = X[(X.dtype == np.int64) & (np.sum(X, axis=1) == n)]

print(selected_rows)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)


In [ ]:

# Set the random seed for reproducibility
np.random.seed(42)

# Define the 1D array X
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Number of bootstrap samples
N = 1000

# Perform bootstrapping
bootstrap_means = []
for _ in range(N):
    # Resample with replacement
    bootstrap_sample = np.random.choice(X, size=len(X), replace=True)
    # Compute the mean of the bootstrap sample
    bootstrap_mean = np.mean(bootstrap_sample)
    bootstrap_means.append(bootstrap_mean)

# Compute the 95% confidence interval
confidence_interval = np.percentile(bootstrap_means, [2.5, 97.5])

print("Bootstrapped 95% Confidence Interval:", confidence_interval)